sudo: required
services:
  - docker

before_install:
  - docker build -t rommek1985/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rommek1985/react-test npm test

after_success:
  - docker build -t rommek1985/multi-client ./client
  - docker build -t rommek1985/multi-nginx ./nginx
  - docker build -t rommek1985/multi-server ./server
  - docker build -t rommek1985/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rommek1985/multi-client
  - docker push rommek1985/multi-nginx
  - docker push rommek1985/multi-server
  - docker push rommek1985/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env-1
  bucket_name: elasticbeanstalk-us-east-2-904638673515
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY